/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AGrid: typeof import('@ayingott/a-grid')['AGrid']
    AGridItem: typeof import('@ayingott/a-grid')['AGridItem']
  }
}
